### PR TITLE
Persist DB metadata when Rafiki is stopped & restarted

### LINKED ISSUE #19: Persist metadata when Rafiki is stopped

### PR DESCRIPTION
**Pull request by nginyc**
Fixes #19 

GIVEN Rafiki admin has started Rafiki, model developers have created a few models, and application developers have run a few train/inference jobs
WHEN the admin restarts Rafiki with `scripts/stop.sh` and `scripts/start.sh`
THEN Rafiki's user, job & model data should persist

@cadmusthefounder to test & verify that this works

### CODE REVIEW

**Comment by wild-flame** [comment]
the first time i run `sudo bash script/start.sh` is fine, but after i run `sudo bash scripts/stop.sh`

the second time i run `sudo bash script/start.sh`, I would see

```
---------------------------
| Starting Rafiki's DB... |
---------------------------
Waiting for 20s for Rafiki's DB to stabilize...
Error running Rafiki's DB
Check the logs at /home/david/coding/rafiki/rafiki/logs/start_db.log
```

 error in `/home/david/coding/rafiki/rafiki/logs/start_db.log`

```
docker: Error response from daemon: Conflict. The container name "/rafiki_db" is already in use by container "2e02c89b2b80b4f7abaaf26ad2e804f5c1c09aa64e8e8053afbc4826b4a9badc". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```

I double checked `sudo bash script/stop.sh` and noticed that it got

``` bash
~/coding/rafiki/rafiki$ sudo bash scripts/stop.sh
---------------------------------
| Stopping any existing jobs... |
---------------------------------
{'inference_jobs': [], 'train_jobs': []}
-----------------------
| Dumping database... |
-----------------------
Database dump file exists at /home/david/coding/rafiki/rafiki/db_dump.sql. Override it? (y/n) y
Dumping database to /home/david/coding/rafiki/rafiki/db_dump.sql...
pg_dump: [archiver (db)] connection to database "rafiki" failed: FATAL:  role "postgres" does not exist
```
```
~/coding/rafiki/rafiki$ sudo bash scripts/stop.sh
---------------------------------
| Stopping any existing jobs... |
---------------------------------
{'inference_jobs': [], 'train_jobs': []}
-----------------------
| Dumping database... |
-----------------------
Database dump file exists at /home/david/coding/rafiki/rafiki/db_dump.sql. Override it? (y/n) n
Not dumping database!
```

whether i chose to dumping or not, the bash would exit without execute the code in `stop.sh` after
```
bash ./scripts/save_db.sh || exit 1
```

Did you intentionally make the shell exit? I guess either `stop.sh` or `start.sh` should be changed accordingly.

**Comment by wild-flame** [comment]
I changed the code in `save_db.sh`

```
then 
    echo "Not dumping database!" 
    exit 1
fi
```

to

```
then 
    echo "Not dumping database!" 
    exit 0
fi
```
which seems to be a fix.

**Comment by nginyc** [comment]
Thanks for the catch. This is because my code doesn't properly handle an error while dumping the database.  I'll be pushing a fix.

After implementing your own fix, does the code work?

**Comment by nginyc** [comment]
@wild-flame I've pushed a fix. Let me know if this change works as described. Thanks!

**Pull request merged**
