### PR TITLE
Switch UI to new design

### LINKED ISSUE #105: User to manage inference job on Rafiki Web Admin
- [x] User to create train job on web
- [x] User to create inference job on web
- [x] User to make predictions on web
- [x] User to stop inference job on web

### PR DESCRIPTION
**Pull request by wild-flame**
Fixes #105 
Same as #109 

### Datasets

- Show Datasets List
- Create Datasets

### Trainjobs

-  Able to Create TrainJob
     - Get available datasets list
     - Get available model list 
-  Display TrainsJobs
-  Display Trials
-  Display Trail Details

### Running development

How to test on local machine (may need to run `source env.sh`)
```
$ yarn install 
$ yarn start
```

### CODE REVIEW

**Comment by nginyc** [comment]
If possible, you should remove/correct all template metadata from the template were you using. E.g. in `bower.json`, `package.json`, `public/manifest.json`

**Comment by nginyc** [comment]
Integrated your changes with the deployment of the complete Rafiki stack. You should now be able to run a local instance of Rafiki together with your new front-end.

**Comment by nginyc** [comment]
Hi @wild-flame, I've merged the latest changes from `v0.1.0` into this branch and did some fixing. 
Managed to get the web admin running integrated with the whole Rafiki stack when I run `bash scripts/start.sh`, and the train jobs page, train job detail page (image below) and the trial detail page seem to be working! However, the changes in APIs for creation of train job & new dataset management API might have broken other parts of the front-end (e.g. the create train job UI). Believe you are working on it.  

Screenshot from 2019-06-14 02-18-10

Take note that in my latest commits, the additional `app.js` and extra dependencies in `package.json` are for the Docker-based deployment of the web admin (see the `web_admin.Dockerfile`).

**Comment by wild-flame** [comment]
image

Finish Dataset Uploading, now will alter the create train job page to match the new API

**Comment by nginyc** [comment]
Hi @wild-flame, I've merged the latest changes from `v0.1.0`, did some fixing, and tested the latest changes in this branch!

Feedback on UI:
- Creating of datasets on the UI was working for me! Both from file system & URL 
- But the instructions on the create dataset page is inaccurate for now:
  - The dataset format should conform to the current task specification at https://nginyc.github.io/rafiki/docs/latest/docs/src/user/datasets.html#dataset-type-image-files. Although we want to support the dataset format you described (directories of images), let's do that in a separate PR so that there won't be so many changes for this PR (will be adding an issue for this)
  - Application developers have to separately split their datasets into train & validation, and create 2 datasets separately. Regarding having Rafiki to do this dataset splitting, again, let's do that in a separate PR
- But when I've created a dataset, the create dataset page remains. It should navigate away from the page
- May want to do some form validation on the create dataset page
- Able to view the datasets I have on the new UI (screenshot below)
- But when I click on a dataset, the URL changes but not the page. Subsequently, when I click on the "New Dataset" button, the create dataset page doesn't appear. Maybe should disable this?

Screenshot from 2019-06-15 05-03-17

**Comment by wild-flame** [comment]
The rest features are to be implemented in separate PRs related to issue #125 #122 #118

**Comment by nginyc** [comment]
Hey @wild-flame thanks for the updates! I've checked all the listed functionality and it all works. However, I had do some correction of English, and I believe we should touch-up on the UI more down the road e.g. consistent & sufficient whitespace between UI elements. I'll be merging this PR!

**Pull request merged**
